version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: $PG_URL
    depends_on:
      - db
    volumes:
      - .:/api/var/www
      - rails_log:/api/log
    stdin_open: true
    tty: true
    ports:
      - 4000:4000

  client:
    build:
      context: ./client
      dockerfile: development.Dockerfile
    env_file: .env
    depends_on:
      - api
    volumes:
      - .:/client/var/www
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

  db:
    image: postgres:14-alpine
    healthcheck:
      test: "pg_isready -U postgres"
    env_file: .env
    environment:
      POSTGRES_PASSWORD: postgres
      PSQL_HISTFILE: /root/log/.psql_history
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  rails_log:
