default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("PG_URL") %>

development:
  <<: *default
  database: loyalty_development
  
test:
  <<: *default
  
production:
  <<: *default
  database: loyalty_production
